### ISSUE TITLE
Breaks clipboard integration

### ISSUE THREAD

**Issue by mikekreeki** [bfredl/nvim-miniyank#1]
`nvim-miniyank` breaks system clipboard integration set up with `set clipboard=unnamed,unnamedplus`. Many users have this set up. Any ideas whether this is easily fixable?

Thanks, cool plugin anyway.

**Comment by bfredl** [comment]
Yes, the fix is neovim/neovim#5042. Thanks for reporting!

**Comment by bfredl** [comment]
fixed in neovim master.
