### ISSUE TITLE
Invalid miniyank.mpack file path on Windows

### ISSUE THREAD

**Issue by guhetier** [bfredl/nvim-miniyank#17]
When using nvim-miniyank on Windows, the default file path off miniyank.mpack is invalid
(/temp/user/miniyank.mpack does not exist).

The issue can be easily solved by using 'let g:miniyank_filename = "C:\foo\miniyank.mpack"',
but a working default value on windows would be nice.

**Comment by bfredl** [comment]
I think we can use `stdpath()` on windows. E g does `stdpath('data')` or `stdpath('cache')` give sensible locations for you?

**Comment by guhetier** [comment]
`stdpath()` is probably a good way to go, however I won't be able to test it on windows before Tuesday.
I will tell you then.

**Comment by guhetier** [comment]
I got `stdpath('data')` -> `C:\User\username\AppDataLocal\nvim-data` and `stdpath('cache')` -> `C:\User\USERN~1\AppData\Local\Temp\nvim`.

Both seems valid path for the miniyank.mpack (I think the second one is more adapted for temporary data).

**Comment by bfredl** [comment]
@xNephe I added `stdpath('cache')` fallback, would you mind testing if it now works without `g:miniyank_filename` override?

**Comment by guhetier** [comment]
@bfredl I had to create the folder nvim manually in Temp. Ideally, it should be automatically created.
Once the folder created, everything seems fine.

**Comment by bfredl** [comment]
> Ideally, it should be automatically created.

Fixed.
