### ISSUE TITLE
Count paste broken

### ISSUE THREAD

**Issue by kurkale6ka** [bfredl/nvim-miniyank#2]
Hi, I use the following mappings:

```
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)

map <c-n> <Plug>(miniyank-cycle)
```

Basically, count is ignored when pasting. So 5p pastes a single line only for instance

**Comment by bfredl** [comment]
Thanks for the report! Please try latest commit.

**Comment by kurkale6ka** [comment]
It works now. Thanks
