### ISSUE TITLE
Miniyank only works once

### ISSUE THREAD

**Issue by ntcong** [bfredl/nvim-miniyank#5]
I have this config 

```
Plug 'bfredl/nvim-miniyank'
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)

map <C-p> <Plug>(miniyank-cycle)
```

Then I tried to yank three lines (1,2 and 3), paste (got 3) and use C-p to cycle. Miniyank will just cycle once to previous (replace 3 with 2), and stop working after that.
I'm using neovim 0.1.5 with clipboard=unnamedplus

**Comment by ntcong** [comment]
I think it's because I had an autocmd TextChanged for Neomake, removing it fixes the problem

**Comment by bfredl** [comment]
Yes, if `TextChanged` does something that changes `b:changedtick`, it will not work.

**Comment by ntcong** [comment]
Thank you I think it worth noting so people won't have the same issue.
