### ISSUE TITLE
Can't 'put' on OSX

### ISSUE THREAD

**Issue by bluddy** [bfredl/nvim-miniyank#7]
I've set up $XDG_RUNTIME_DIR and mapped p/P as shown, and I can see the file being created in the directory when I yank. However, nothing happens when I press p/P.

**Comment by bfredl** [comment]
I assume you use
```
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)
```
? Does anything happen if you use miniyank-cycle mapping right after?
If you do `:echo miniyank#read()[0]` will it contain the yanked text?

**Comment by bluddy** [comment]
I was using noremap and it wasn't working. Does noremap not work in neovim?

**Comment by bfredl** [comment]
`noremap` only works for mapping to builtin keybindings. To map to a plugin-defined mapping like `<Plug>(miniyank-autoput)` ordinary `map` must be used. This is the same in vim and neovim.

**Comment by bluddy** [comment]
Thanks for the explanation! Sorry for the noise. Closing.
